### ISSUE TITLE
bug: Unhandled 'error' event (events.js:72)

### ISSUE THREAD

**Issue by sabriibrahim** [ajmalafif/sixleaves#1]
I got this error when I run `$ gulp` 

```
[14:22:42] Using gulpfile ~/Sites/sixleaves/gulpfile.js
[14:22:42] Starting 'sass'...
[14:22:42] Starting 'jekyll-build'...
[14:22:42] Starting 'watch'...
[14:22:42] Finished 'watch' after 16 ms
[14:22:42] Starting 'bower'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by ajmalafif** [comment]
Solved by @sabriibrahim https://github.com/ajmalafif/sixleaves/pull/2
